### ISSUE TITLE
pull requests

### ISSUE THREAD

**Issue by hoobhoobhoob** [Kuna42/start-projects#1]
How do you use pull requests? I think we had to submit the code in pull requests but it just kind of doesn't work

**Comment by hoobhoobhoob** [comment]
I would like to submit my code

**Comment by hoobhoobhoob** [comment]
plz

**Comment by Kuna42** [comment]
I don't have a English version of how to create a pull request, but...
_I know you know German ;)_
Du kannst [Pull requests](https://github.com/Kuna42/start-projects/wiki/Eigener-Code) so erstellen. Ich muss das Wiki noch etwas überarbeiten, aber ich hoffe diese Version reicht aus um welche erstellen zu können.

*if you want to help me to improve the wiki, you can send in a pull request a new wiki page ;)*
